# 使用pickle序列化numpy array

In [2]:
import pickle
import numpy as np

In [5]:
x = np.arange(10)

In [6]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
f = open('x.pkl', 'wb')

In [8]:
pickle.dump(x, f)

In [9]:
!ls

Array.ipynb                  demo.ipynb
Array的input和output.ipynb   x.pkl
README.md                    数组与矩阵运算.ipynb


In [10]:
f = open('x.pkl', 'rb')

In [11]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## np本身的序列化

In [12]:
np.save('one_array', x)

In [13]:
!ls

Array.ipynb                  one_array.npy
Array的input和output.ipynb   x.pkl
README.md                    数组与矩阵运算.ipynb
demo.ipynb


In [14]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
y = np.arange(20)

In [16]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
np.savez('two_array.npz', a=x, b=y)

In [18]:
!ls

Array.ipynb                  one_array.npy
Array的input和output.ipynb   two_array.npz
README.md                    x.pkl
demo.ipynb                   数组与矩阵运算.ipynb


In [20]:
c = np.load('two_array.npz')

In [21]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

> Numpy[文档地址](https://www.numpy.org/doc/)