# 快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([-0.40215515, -1.17227585, -0.37205103,  0.37077264,  0.09358873,
        0.2384216 ,  0.12565273, -1.711381  ,  0.22684689, -0.66881186])

In [4]:
np.random.randint(10, size=(2,3))

array([[0, 6, 3],
       [1, 9, 6]])

In [6]:
np.random.randint(10, size=20).reshape(4,5)

array([[2, 9, 8, 4, 6],
       [6, 0, 4, 6, 5],
       [5, 0, 6, 4, 9],
       [7, 7, 4, 4, 3]])

# 数组运算

In [7]:
a = np.random.randint(10, size=20).reshape(4, 5)

In [8]:
b = np.random.randint(10, size=20).reshape(4, 5)

In [9]:
a

array([[5, 7, 5, 2, 8],
       [0, 5, 0, 6, 5],
       [5, 7, 1, 4, 3],
       [3, 7, 6, 1, 4]])

In [10]:
b

array([[2, 5, 0, 2, 5],
       [1, 3, 6, 5, 4],
       [9, 6, 3, 4, 0],
       [8, 1, 7, 5, 7]])

In [11]:
a + b

array([[ 7, 12,  5,  4, 13],
       [ 1,  8,  6, 11,  9],
       [14, 13,  4,  8,  3],
       [11,  8, 13,  6, 11]])