# 快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([-0.40215515, -1.17227585, -0.37205103,  0.37077264,  0.09358873,
        0.2384216 ,  0.12565273, -1.711381  ,  0.22684689, -0.66881186])

In [4]:
np.random.randint(10, size=(2,3))

array([[0, 6, 3],
       [1, 9, 6]])

In [6]:
np.random.randint(10, size=20).reshape(4,5)

array([[2, 9, 8, 4, 6],
       [6, 0, 4, 6, 5],
       [5, 0, 6, 4, 9],
       [7, 7, 4, 4, 3]])

# 数组运算

In [27]:
a = np.random.randint(10, size=(4, 5))

In [28]:
a

array([[6, 5, 6, 4, 3],
       [2, 8, 9, 5, 5],
       [1, 4, 6, 5, 6],
       [9, 3, 4, 1, 3]])

In [7]:
a = np.random.randint(10, size=20).reshape(4, 5)

In [8]:
b = np.random.randint(10, size=20).reshape(4, 5)

In [9]:
a

array([[5, 7, 5, 2, 8],
       [0, 5, 0, 6, 5],
       [5, 7, 1, 4, 3],
       [3, 7, 6, 1, 4]])

In [10]:
b

array([[2, 5, 0, 2, 5],
       [1, 3, 6, 5, 4],
       [9, 6, 3, 4, 0],
       [8, 1, 7, 5, 7]])

In [11]:
a + b

array([[ 7, 12,  5,  4, 13],
       [ 1,  8,  6, 11,  9],
       [14, 13,  4,  8,  3],
       [11,  8, 13,  6, 11]])

In [12]:
a - b

array([[ 3,  2,  5,  0,  3],
       [-1,  2, -6,  1,  1],
       [-4,  1, -2,  0,  3],
       [-5,  6, -1, -4, -3]])

In [13]:
a * b

array([[10, 35,  0,  4, 40],
       [ 0, 15,  0, 30, 20],
       [45, 42,  3, 16,  0],
       [24,  7, 42,  5, 28]])

In [14]:
a / b

/Users/charlielee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[2.5       , 1.4       ,        inf, 1.        , 1.6       ],
       [0.        , 1.66666667, 0.        , 1.2       , 1.25      ],
       [0.55555556, 1.16666667, 0.33333333, 1.        ,        inf],
       [0.375     , 7.        , 0.85714286, 0.2       , 0.57142857]])

In [15]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [16]:
np.mat(a)

matrix([[5, 7, 5, 2, 8],
        [0, 5, 0, 6, 5],
        [5, 7, 1, 4, 3],
        [3, 7, 6, 1, 4]])

# 矩阵的计算

In [17]:
A = np.mat(a)

In [18]:
B = np.mat(b)

In [20]:
A

matrix([[5, 7, 5, 2, 8],
        [0, 5, 0, 6, 5],
        [5, 7, 1, 4, 3],
        [3, 7, 6, 1, 4]])

In [21]:
B

matrix([[2, 5, 0, 2, 5],
        [1, 3, 6, 5, 4],
        [9, 6, 3, 4, 0],
        [8, 1, 7, 5, 7]])

In [22]:
A + B

matrix([[ 7, 12,  5,  4, 13],
        [ 1,  8,  6, 11,  9],
        [14, 13,  4,  8,  3],
        [11,  8, 13,  6, 11]])

In [23]:
A - B

matrix([[ 3,  2,  5,  0,  3],
        [-1,  2, -6,  1,  1],
        [-4,  1, -2,  0,  3],
        [-5,  6, -1, -4, -3]])

In [24]:
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [26]:
a = np.mat(np.random.randint(10, size=20).reshape(4,5))
b = np.mat(np.random.randint(10, size=20).reshape(5,4))

In [29]:
a

array([[6, 5, 6, 4, 3],
       [2, 8, 9, 5, 5],
       [1, 4, 6, 5, 6],
       [9, 3, 4, 1, 3]])

In [30]:
b

matrix([[1, 2, 2, 6],
        [6, 4, 4, 3],
        [9, 7, 1, 5],
        [0, 9, 1, 1],
        [6, 4, 7, 7]])

In [31]:
a * b

matrix([[108, 122,  63, 106],
        [161, 164,  85, 121],
        [115, 129,  71,  95],
        [ 81,  79,  56, 105]])

# Array常用函数

In [33]:
a = np.random.randint(10, size=(4, 5))

In [39]:
np.unique(a)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a

array([[5, 3, 0, 8, 0],
       [7, 1, 4, 5, 0],
       [6, 4, 9, 9, 3],
       [3, 3, 6, 6, 6]])

In [41]:
sum(a) #列的和

array([21, 11, 19, 28,  9])

In [42]:
sum(a[0]) #第一行的和

16

In [43]:
sum(a[:, 0]) #第一列的和

21

In [44]:
a.max() #a的最大值

9

In [45]:
max(a[0]) #a行的最大值

8

In [46]:
max(a[:, 0]) #a列的最大值

7